default:
  primary: yahoo
  fallback:
    - moex

exchanges:
  MOEX:
    primary: moex
    fallback:
      - yahoo
  NASDAQ:
    primary: yahoo
    fallback: []
  NYSE:
    primary: yahoo
    fallback: []
  CRYPTO:
    primary: crypto
    fallback:
      - yahoo
